allowBuilds:
  '@parcel/watcher': false
  unrs-resolver: false
  '@scarf/scarf': false
  esbuild: true
  serverless: true
overrides:
  ajv@6.15.0>uri-js: npm:fast-uri@3.1.8
  jest-config@30.5.2>deepmerge: 4.1.2
