AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Type: String
    Default: rimac-learning
  Stage:
    Type: String
    Default: learning
Resources:
  SwaggerSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub ${ProjectName}/${Stage}/swagger
      GenerateSecretString:
        SecretStringTemplate: '{"username":"admin"}'
        GenerateStringKey: password
        PasswordLength: 32
Outputs:
  SwaggerSecretArn:
    Value: !Ref SwaggerSecret
